# Generated by Django 4.1.7 on 2023-02-24 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Sektor nomi")),
                (
                    "leader",
                    models.ForeignKey(
                        help_text="Sektor raxbarini tanlang",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Mahalla nomi")),
                (
                    "leader",
                    models.ForeignKey(
                        help_text="Sektor raxbarini tanlang",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        help_text="Mahalla qaysi sektorga tegishli ekanligini tanlang",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mahalla.sector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255, verbose_name="F.I.O.")),
                (
                    "passport",
                    models.CharField(max_length=20, verbose_name="Pasport seriyasi"),
                ),
                ("birthdate", models.DateField(verbose_name="Tug`ilgan sanasi")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Erkak"), ("female", "Ayol")],
                        max_length=255,
                        verbose_name="Fuqoro jinsi",
                    ),
                ),
                (
                    "educated",
                    models.CharField(
                        choices=[
                            ("middle", "O'rta ma'lumotli"),
                            ("senior", "Oliy ma'lumotli"),
                        ],
                        max_length=255,
                        verbose_name="Fuqoro ma'lumoti",
                    ),
                ),
                ("address", models.TextField(verbose_name="Fuqoro manzili")),
                (
                    "iron_notebook",
                    models.CharField(
                        choices=[("yes", "ha"), ("no", "yo'q")],
                        max_length=255,
                        verbose_name="Temir daftarda bormi",
                    ),
                ),
                (
                    "abroad",
                    models.CharField(
                        choices=[("yes", "ha"), ("no", "yo'q")],
                        max_length=255,
                        verbose_name="Xozir chet eldami",
                    ),
                ),
                (
                    "disabiltiy",
                    models.CharField(
                        choices=[("yes", "ha"), ("no", "yo'q")],
                        max_length=20,
                        verbose_name="Nogironligi bormi",
                    ),
                ),
                (
                    "womens_notebook",
                    models.BooleanField(
                        choices=[("yes", "ha"), ("no", "yo'q")],
                        max_length=20,
                        verbose_name="Ayollar daftarida bormi",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mahalla.neighborhood",
                        verbose_name="Mahallani tanlang",
                    ),
                ),
            ],
        ),
    ]
