# Generated by Django 4.1.7 on 2023-02-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="womens_notebook",
            field=models.TextField(
                choices=[("yes", "ha"), ("no", "yo'q")],
                max_length=20,
                verbose_name="Ayollar daftarida bormi",
            ),
        ),
    ]
