# Generated by Django 4.1.7 on 2023-02-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0003_alter_citizen_womens_notebook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="womens_notebook",
            field=models.CharField(
                max_length=20, verbose_name="Ayollar daftarida bormi"
            ),
        ),
    ]
