# Generated by Django 4.1.7 on 2023-02-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0004_alter_citizen_womens_notebook"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neighborhood",
            name="leader",
        ),
        migrations.RemoveField(
            model_name="sector",
            name="leader",
        ),
    ]
