# Generated by Django 4.1.7 on 2023-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0006_alter_citizen_options_alter_neighborhood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="womens_notebook",
            field=models.CharField(
                choices=[("yes", "ha"), ("no", "yo'q")],
                max_length=20,
                verbose_name="Ayollar daftarida bormi",
            ),
        ),
    ]
