# Generated by Django 4.1.7 on 2023-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0007_alter_citizen_womens_notebook"),
    ]

    operations = [
        migrations.AddField(
            model_name="citizen",
            name="pensioner",
            field=models.CharField(
                choices=[("yes", "ha"), ("no", "yo'q")],
                max_length=255,
                null=True,
                verbose_name="Pensiyoner",
            ),
        ),
    ]
