# Generated by Django 4.1.7 on 2023-02-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0005_remove_neighborhood_leader_remove_sector_leader"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.AddField(
            model_name="user",
            name="neighborhood",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mahalla.neighborhood",
                verbose_name="Qaysi mahalla rahbari",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="sector",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mahalla.sector",
                verbose_name="Qaysi sektor rahbari",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("sector_leader", "Sektor rahbari"),
                    ("nighborhood_leader", "Mahalla rahbari"),
                    ("measures", "Hokim"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=255,
                verbose_name="Foydalanuvchi turi",
            ),
            preserve_default=False,
        ),
    ]
