# Generated by Django 4.1.7 on 2023-02-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_user_options_alter_user_birthday_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Telefon raqami"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("sector_leader", "Sektor rahbari"),
                    ("nighborhood_leader", "Mahalla rahbari"),
                    ("measures", "Hokim"),
                    ("admin", "Admin"),
                ],
                default="nighborhood_leader",
                max_length=255,
                verbose_name="Foydalanuvchi turi",
            ),
        ),
    ]
