# Generated by Django 4.1.7 on 2023-02-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_user_phone_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Telefon raqami"
            ),
        ),
    ]
